# 机器人的昵称，可配置多个
nick_name:
    - "小风"
# bot超级管理员账户
admin: 0
# bot运行地址，若和gocq在同一台机器则只需要填写127.0.0.1即可，否则填写0.0.0.0，gocq配置你的公网地址
host: 127.0.0.1
# bot运行端口
port: 8080
# access_token
token: ""
# leafBot日志等级
log_level: info
# bot的管理员用户，类型为数组
super_user:
    - 123456
#    - 123456

# 配置命令的起始字符
command_start:
    - ""
    - /
# 是否启用playwright。热搜插件以及网页截图插件会依赖于该配置
enable_playwright: false

# 日志是否截断,默认截断
log_truncate: true

# cqhttp_http_driver监听地址
listen_host: 127.0.0.1

# cqhttp_http_driver监听断开
listen_port: 8081

# cqhttp_http_driver一个bot实例，即onebot端所监听的api地址以及账号
web_hook:
    -
        post_host: 127.0.0.1
        post_port: 5700
        self_id: 1603214019

